name: Create File Workflow

on:
  push:
    branches: [ main ]      # runs on every push to main
  workflow_dispatch:        # allows manual/API trigger

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a file
        run: echo "Hello from GitHub Actions 🚀" > hello.txt

      - name: Show file contents
        run: cat hello.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-file
          path: hello.txt
